version: 2.1
orbs:
  docker: circleci/docker@1.5.0
jobs:
  build:
    executor: docker/machine
    steps:
      - checkout
      - docker/check:
          docker-username: DOCKER_LOGIN
          docker-password: DOCKER_PASSWORD
          registry: docker.io
      - docker/build:
          dockerfile: Dockerfile
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
workflows:
  master:
    jobs:
      - build